service: indent-access-request-webhook
provider:
  name: aws

plugins:
  - serverless-plugin-typescript

functions:
  webhook:
    runtime: nodejs8.10
    events:
      - http:
          method: post
          path: webhook
          cors:
            origin: '*'
            headers:
              - X-Indent-Signature
              - X-Indent-Timestamp
    handler: index.handle
