name: all
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/build-and-test.yml
      - 'packages/**'
jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: setup-node
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: deps-and-test
        run: |
          make test
